// <auto-generated />
using M06.RateLimiting.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace M06.RateLimiting.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("M06.RateLimiting.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Soda",
                            Price = 1.99m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Milk",
                            Price = 3.49m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Orange Juice",
                            Price = 4.75m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bread",
                            Price = 2.49m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Butter",
                            Price = 3.99m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Eggs",
                            Price = 2.99m
                        },
                        new
                        {
                            Id = 7,
                            Name = "Cheese",
                            Price = 5.49m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Chocolate",
                            Price = 1.99m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Coffee",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = 10,
                            Name = "Tea",
                            Price = 4.99m
                        },
                        new
                        {
                            Id = 11,
                            Name = "Water",
                            Price = 0.99m
                        },
                        new
                        {
                            Id = 12,
                            Name = "Fruit Mix Juice",
                            Price = 3.99m
                        },
                        new
                        {
                            Id = 13,
                            Name = "Yogurt",
                            Price = 2.99m
                        },
                        new
                        {
                            Id = 14,
                            Name = "Cereal",
                            Price = 4.49m
                        },
                        new
                        {
                            Id = 15,
                            Name = "Rice",
                            Price = 6.99m
                        },
                        new
                        {
                            Id = 16,
                            Name = "Pasta",
                            Price = 3.49m
                        },
                        new
                        {
                            Id = 17,
                            Name = "Apple",
                            Price = 0.79m
                        },
                        new
                        {
                            Id = 18,
                            Name = "Banana",
                            Price = 0.59m
                        },
                        new
                        {
                            Id = 19,
                            Name = "Orange",
                            Price = 0.99m
                        },
                        new
                        {
                            Id = 20,
                            Name = "Grapes",
                            Price = 2.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
