@baseUrl = https://localhost:5151

@projectId = f5aae296-97dc-4a2b-a15a-b20ce4780d3a
@taskId = b7cc98df-bcce-4bed-be26-d734797549c8


###

POST {{baseUrl}}/api/token/generate
content-type: application/json

{
  "Id": "79410514-0136-4442-be9b-01f097c57f7a",
  "FirstName": "Primary",
  "LastName": "Manager",
  "Email": "pm@localhost",
  "Permissions": [
    "project:create",
    "project:read",
    "project:update",
    "project:delete",
    "project:assign_member",
    "project:manage_budget",
    "task:create",
    "task:read",
    "task:update",
    "task:delete",
    "task:assign_user",
    "task:update_status"
  ],
  "Roles": [
    "ProjectManager"
  ]
}

###
POST {{baseUrl}}/api/token/generate
content-type: application/json

{
  "Id": "b1c2d3e4-f5g6-7h8i-9j0k-1l2m3n4o5p6q",
  "FirstName": "John",
  "LastName": "Doe",
  "Email": "john.doe@localhost",
  "Permissions": [
    "project:read",
    "task:read",
    "task:update_status",
    "task:comment"
  ],
  "Roles": [
    "TeamMember"
  ]
}

###

POST {{baseUrl}}/api/token/generate
content-type: application/json

{
  "Id": "c7d8e9f0-g1h2-i3j4-k5l6-m7n8o9p0q1r2",
  "FirstName": "Emily",
  "LastName": "White",
  "Email": "emily.white@localhost",
  "Permissions": [
    "project:read",
    "task:read"
  ],
  "Roles": [
    "Stakeholder"
  ]
}

###
GET {{baseUrl}}/api/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMWMyZDNlNC1mNWc2LTdoOGktOWoway0xbDJtM240bzVwNnEiLCJlbWFpbCI6ImpvaG4uZG9lQGxvY2FsaG9zdCIsImZhbWlseV9uYW1lIjoiRG9lIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJyb2xlIjoiVGVhbU1lbWJlciIsInBlcm1pc3Npb24iOlsicHJvamVjdDpyZWFkIiwidGFzazpyZWFkIiwidGFzazp1cGRhdGVfc3RhdHVzIiwidGFzazpjb21tZW50Il0sIm5iZiI6MTc0ODI5NTU0NSwiZXhwIjoxNzQ4Mjk2MTQ1LCJpYXQiOjE3NDgyOTU1NDUsImlzcyI6ImxvY2FsaG9zdCIsImF1ZCI6ImxvY2FsaG9zdCJ9.b-8AwmC0aXbyMpWcpreUHaLxIfkJOCx6yuwjCMOpUJo

###
GET {{baseUrl}}/api/projects/{{projectId}}


###
POST {{baseUrl}}/api/projects
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMWMyZDNlNC1mNWc2LTdoOGktOWoway0xbDJtM240bzVwNnEiLCJlbWFpbCI6ImpvaG4uZG9lQGxvY2FsaG9zdCIsImZhbWlseV9uYW1lIjoiRG9lIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJyb2xlIjoiVGVhbU1lbWJlciIsInBlcm1pc3Npb24iOlsicHJvamVjdDpyZWFkIiwidGFzazpyZWFkIiwidGFzazp1cGRhdGVfc3RhdHVzIiwidGFzazpjb21tZW50Il0sIm5iZiI6MTc0ODI5NTY2MCwiZXhwIjoxNzQ4Mjk2MjYwLCJpYXQiOjE3NDgyOTU2NjAsImlzcyI6ImxvY2FsaG9zdCIsImF1ZCI6ImxvY2FsaG9zdCJ9.z2CBUswNe_ROBdH1soYFTF6svGLRFWhCZFJW4SBzPfc


###
PUT {{baseUrl}}/api/projects/{{projectId}}
Content-Type: application/json


###
DELETE {{baseUrl}}/api/projects/{{projectId}}


###
POST {{baseUrl}}/api/projects/{{projectId}}/members

###
GET {{baseUrl}}/api/projects/{{projectId}}/budget


###
POST {{baseUrl}}/api/projects/tasks
Content-Type: application/json


###
GET {{baseUrl}}/api/projects/tasks/{{taskId}}

###
PUT {{baseUrl}}/api/projects/tasks/{{taskId}}
Content-Type: application/json


###
DELETE {{baseUrl}}/api/projects/tasks/{{taskId}}

###
POST {{baseUrl}}/api/projects/tasks/{{taskId}}/assign
Content-Type: application/json


###
PUT {{baseUrl}}/api/projects/tasks/{{taskId}}/status
Content-Type: application/json

