@baseUrl = https://localhost:7272

POST {{baseUrl}}/api/products
Content-Type: application/json

{
  "name": "Smart Watch Pro X",
  "description": "High-end smartwatch with GPS",
  "sku": "PRD-00121",
  "price": 249.99,
  "stockQuantity": 1 ,
  "launchDate": "2025-05-22",
  "category": "Electronics",
  "imageUrl": "https://cdn.example.com/products/watch.jpg",
  "weight": 0.4,
  "warrantyPeriodMonths": 12,
  "isReturnable": true,
  "returnPolicyDescription": "Returns accepted within 30 days with receipt.",
  "tags": ["smartwatch", "gps", "wearable"]
}
