@baseUrl = https://localhost:7062
@productId = 2779ee47-10b0-4bd7-8342-404006aa1392
 
###
GET {{baseUrl}}/api/products?page=1&pageSize=100

###
GET {{baseUrl}}/api/products/{{productId}}?includeReviews=true

### 
POST {{baseUrl}}/api/products
Content-Type: application/json

{
  "name": "Keyboard",
  "price": 34.99
}


###
POST {{baseUrl}}/api/products/{{productId}}/reviews
Content-Type: application/json

{
  "reviewer": "Kevin Kelo",
  "stars": 3
}

### 
PUT {{baseUrl}}/api/products/{{productId}}
Content-Type: application/json

{
    "name": "chocolate bar",
    "price": 3.50
}

### DELETE
DELETE {{baseUrl}}/api/products/{{productId}}
