@baseUrl = https://localhost:7105

### Minimal API

GET {{baseUrl}}/product-minimal/42

### Minimal API 1

GET {{baseUrl}}/product-minimal-1/42

### Minimal API 1

GET {{baseUrl}}/product-minimal-2/42?id=21

### Minimal API
GET {{baseUrl}}/product-controller/43
